apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:

  MONGO_URL: "{{ .Values.secret.mongoUrl }}"

  JWT_SECRET: "{{ .Values.secret.jwtSecret }}"

  EMAIL_USER: "{{ .Values.secret.emailUser }}"

  EMAIL_PASS: "{{ .Values.secret.emailPass }}"