worker_processes auto;

# Store PID in a writable location
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout 65;

    server_tokens off;

    server {

        # Non-root user cannot bind to port 80
        listen 8080;

        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        # React Router Support
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Static Assets
        location /static/ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        # Health Check
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }

        error_page 500 502 503 504 /50x.html;

        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
}
