[PROJECT]
name = HopeGivers

[PARSER]
version = 1.0.0

[HADOLINT]
scanner_version = latest
report_dir = compliance/reports/hadolint
output_dir = compliance/normalized/hadolint

[TRIVY]
scanner_version = latest
report_dir = compliance/reports/trivy
output_dir = compliance/normalized/trivy

[GITLEAKS]
scanner_version = latest
report_dir = compliance/reports/gitleaks
output_dir = compliance/normalized/gitleaks

[ZAP]
scanner_version = latest
report_dir = compliance/reports/zap
output_dir = compliance/normalized/zap
