apiVersion: 1

datasources:
  - name: DevSecOps-MySQL-RDS
    type: mysql
    access: proxy
    url: ${DB_HOST}:3306
    database: ${DB_NAME:devsecops}
    user: ${DB_USER:admin}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
    isDefault: true
    editable: true
